name: dual-nextera-12
top_flanking:
  adapter_side: TCGTCGGCAGCGTCAGATGTG
bottom_flanking:
  adapter_side: GTCTCGTGGGCTCGGAGATGT
length: 12
umi_ends: both
umi_flank_mode: adapter_only
adapter_max_edits: 4
