# Conversion (Bisulfite/APOBEC)footprinting defaults
extends: default

######## smftools load params #########
conversion_types: 
  - '5mC' # 5mC

######## smftools preprocess params #########
# Read QC Params
read_mod_filtering_use_other_c_as_background: True

# Spatial Analysis - Autocorr params
autocorr_site_types:
  - "GpC"

# Spatial Analysis - Clustermap params
layer_for_clustermap_plotting: 'nan0_0minus1'
clustermap_cmap_c: "coolwarm"
clustermap_cmap_gpc: "coolwarm"
clustermap_cmap_cpg: "viridis"
clustermap_cmap_a: "coolwarm"

######## smftools hmm params #########
# HMM
cpg: True # whether to use the default HMM endogenous CpG patch params
hmm_methbases:
  - "GpC"
hmm_feature_sets:
  footprint:
    state: "Non-Modified"
    features:
      small_bound_stretch: [6, 40]
      medium_bound_stretch: [40, 100]
      putative_nucleosome: [100, 200]
      large_bound_stretch: [200, inf]
  accessible:
    state: "Modified"
    features:
      small_accessible_patch: [3, 20]
      mid_accessible_patch: [20, 40]
      large_accessible_patch: [40, 110]
      nucleosome_depleted_region: [110, inf]
  cpg:
    state: "Modified"
    features:
      cpg_patch: [0, inf]

hmm_merge_layer_features:
  - ["all_accessible_features", 60]
