# Deaminase footprinting defaults
extends: default
conversion_types: 
  - '5mC' # 5mC

mod_target_bases:
- "C"

read_mod_filtering_gpc_thresholds:
  - null
  - null
read_mod_filtering_cpg_thresholds:
  - null
  - null
read_mod_filtering_any_c_thresholds:
  - 0.01
  - 0.99
read_mod_filtering_a_thresholds:
  - null
  - null

read_mod_filtering_use_other_c_as_background: False

# Duplicate Detection Params
duplicate_detection_site_types:
  - "any_C"

# Autocorrelation params
autocorr_site_types:
  - "any_C"

# Correlation matrix params
correlation_matrix_site_types:
  - "any_C_site"

# HMM
cpg: False # whether to use the default HMM endogenous CpG patch params
hmm_methbases:
  - "C"
hmm_feature_sets:
  footprint:
    state: "Non-Modified"
    features:
      small_bound_stretch: [0, 25]
      medium_bound_stretch: [25, 80]
      putative_nucleosome: [80, 200]
      large_bound_stretch: [200, inf]
  accessible:
    state: "Modified"
    features:
      small_accessible_patch: [0, 20]
      mid_accessible_patch: [20, 100]
      large_accessible_patch: [100, inf]

hmm_merge_layer_features:
  - ["C_all_accessible_features", 80]