name: SQK-RBK114-24
flanking:
  adapter_side: GCTTGGGTGTTTAACC
  amplicon_side: GTTTTCGCATTTATCGTGAAACGCTTTCGCGTTTTTCGTGCGCCGCTTCA
barcode_ends: both
barcode_flank_mode: either
barcode_max_edit_distance: 5
barcode_adapter_max_edits: 2
barcode_amplicon_max_edits: 10
same_orientation: false
barcodes:
  RB01: AAGAAAGTTGTCGGTGTCTTTGTG
  RB02: TCGATTCCGTTTGTAGTCGTCTGT
  RB03: GAGTCTTGTGTCCCAGTTACCAGG
  RB04: TTCGGATTCTATCGTGTTTCCCTA
  RB05: CTTGTCCAGGGTTTGTGTAACCTT
  RB06: TTCTCGCAAAGGCAGAAAGTAGTC
  RB07: GTGTTACCGTGGGAATGAATCCTT
  RB08: TTCAGGGAACAAACCAAGTTACGT
  RB09: AACTAGGCACAGCGAGTCTTGGTT
  RB10: AAGCGTTGAAACCTTTGTCCTCTC
  RB11: GTTTCATCTATCGGAGGGAATGGA
  RB12: CAGGTAGAAAGAAGCAGAATCGGA
  RB13: AGAACGACTTCCATACTCGTGTGA
  RB14: AACGAGTCTCTTGGGACCCATAGA
  RB15: AGGTCTACCTCGCTAACACCACTG
  RB16: CGTCAACTGACAGTGGTTCGTACT
  RB17: ACCCTCCAGGAAAGTACCTCTGAT
  RB18: CCAAACCCAACAACCTAGATAGGC
  RB19: GTTCCTCGTGCAGTGTCAAGAGAT
  RB20: TTGCGTCCTGTTACGAGAACTCAT
  RB21: GAGCCTCTCATTGTCCGTTCTCTA
  RB22: ACCACTGCCATGTATCAAAGTACG
  RB23: CTTACTACCCAGTGAACCTCCTCG
  RB24: GCATAGTTCTGCATGATGGGTTAG
