name: SQK-NBD114-24
flanking:
  adapter_side: AAGGTTAA
  amplicon_side: CAGCACCT
  adapter_pad: 5
  amplicon_pad: 5
barcode_ends: both
barcode_max_edit_distance: 6
barcode_composite_max_edits: 8
barcode_min_separation: 2
barcodes:
  NB01: CACAAAGACACCGACAACTTTCTT
  NB02: ACAGACGACTACAAACGGAATCGA
  NB03: CCTGGTAACTGGGACACAAGACTC
  NB04: TAGGGAAACACGATAGAATCCGAA
  NB05: AAGGTTACACAAACCCTGGACAAG
  NB06: GACTACTTTCTGCCTTTGCGAGAA
  NB07: AAGGATTCATTCCCACGGTAACAC
  NB08: ACGTAACTTGGTTTGTTCCCTGAA
  NB09: AACCAAGACTCGCTGTGCCTAGTT
  NB10: GAGAGGACAAAGGTTTCAACGCTT
  NB11: TCCATTCCCTCCGATAGATGAAAC
  NB12: TCCGATTCTGCTTCTTTCTACCTG
  NB13: AGAACGACTTCCATACTCGTGTGA
  NB14: AACGAGTCTCTTGGGACCCATAGA
  NB15: AGGTCTACCTCGCTAACACCACTG
  NB16: CGTCAACTGACAGTGGTTCGTACT
  NB17: ACCCTCCAGGAAAGTACCTCTGAT
  NB18: CCAAACCCAACAACCTAGATAGGC
  NB19: GTTCCTCGTGCAGTGTCAAGAGAT
  NB20: TTGCGTCCTGTTACGAGAACTCAT
  NB21: GAGCCTCTCATTGTCCGTTCTCTA
  NB22: ACCACTGCCATGTATCAAAGTACG
  NB23: CTTACTACCCAGTGAACCTCCTCG
  NB24: GCATAGTTCTGCATGATGGGTTAG
